# Use container-based infrastructure
sudo: false

# Oracle JDK 1.8.0_31 (the default) fails to handle SBT task dependencies properly (a dependent may start too early)
# Oracle JDK 1.8.0_102 handles SBT task dependencies correctly.
addons:
  apt:
    packages:
      - oracle-java8-installer

# These directories are cached to S3 at the end of the build
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

jdk:
- oraclejdk8

language: scala

scala:
- 2.11.8

script:
- ./scripts/travis-build.sh
- ./scripts/travis-deploy.sh

