# Use container-based infrastructure
sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

# These directories are cached to S3 at the end of the build
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
  - "$HOME/.coursier"

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

jdk:
- oraclejdk8

language: scala

scala:
- 2.11.8

script:
- ./scripts/travis-build.sh
- ./scripts/travis-deploy.sh

